// Package upper provides quick access to the uppercase Greek alphabet.
package upper

const Alpha = "Α"
const Beta = "Β"
const Gamma = "Γ"
const Delta = "Δ"
const Epsilon = "Ε"
const Zeta = "Ζ"
const Eta = "Η"
const Theta = "Θ"
const Iota = "Ι"
const Kappa = "Κ"
const Lambda = "Λ"
const Mu = "Μ"
const Nu = "Ν"
const Xi = "Ξ"
const Omicron = "Ο"
const Pi = "Π"
const Rho = "Ρ"
const Sigma = "Σ"
const Tau = "Τ"
const Upsilon = "Υ"
const Phi = "Φ"
const Chi = "Χ"
const Psi = "Ψ"
const Omega = "Ω"
