// Package lower provides quick access to the lowercase Greek alphabet.
package lower

var Alpha = "α"
var Beta = "β"
var Gamma = "γ"
var Delta = "δ"
var Epsilon = "ε"
var Zeta = "ζ"
var Eta = "η"
var Theta = "θ"
var Iota = "ι"
var Kappa = "κ"
var Lambda = "λ"
var Mu = "μ"
var Nu = "ν"
var Xi = "ξ"
var Omicron = "ο"
var Pi = "π"
var Rho = "ρ"
var Sigma = "σ"
var SigmaFinal = "ς"
var Tau = "τ"
var Upsilon = "υ"
var Phi = "φ"
var Chi = "χ"
var Psi = "ψ"
var Omega = "ω"
