package Symbols

// Symbol represents a mathematical symbol.
type Symbol string

const (
	A       Symbol = "a"
	B       Symbol = "b"
	C       Symbol = "c"
	D       Symbol = "d"
	E       Symbol = "e"
	F       Symbol = "f"
	G       Symbol = "g"
	H       Symbol = "h"
	I       Symbol = "i"
	J       Symbol = "j"
	K       Symbol = "k"
	L       Symbol = "l"
	M       Symbol = "m"
	N       Symbol = "n"
	O       Symbol = "o"
	P       Symbol = "p"
	Q       Symbol = "q"
	R       Symbol = "r"
	S       Symbol = "s"
	T       Symbol = "t"
	U       Symbol = "u"
	V       Symbol = "v"
	W       Symbol = "w"
	X       Symbol = "x"
	Y       Symbol = "y"
	Z       Symbol = "z"
	Prime   Symbol = "`"
	Alpha   Symbol = "α"
	Beta    Symbol = "β"
	Gamma   Symbol = "γ"
	Delta   Symbol = "δ"
	Epsilon Symbol = "ε"
	Zeta    Symbol = "ζ"
	Eta     Symbol = "η"
	Theta   Symbol = "θ"
	Iota    Symbol = "ι"
	Kappa   Symbol = "κ"
	Lambda  Symbol = "λ"
	Mu      Symbol = "μ"
	Nu      Symbol = "ν"
	Xi      Symbol = "ξ"
	Omicron Symbol = "ο"
	Pi      Symbol = "π"
	Rho     Symbol = "ρ"
	Sigma   Symbol = "σ"
	Tau     Symbol = "τ"
	Upsilon Symbol = "υ"
	Phi     Symbol = "φ"
	Chi     Symbol = "χ"
	Psi     Symbol = "ψ"
	Omega   Symbol = "ω"
)
