package Symbol

import "JanOS"

const (
	A       JanOS.Symbol = "a"
	B       JanOS.Symbol = "b"
	C       JanOS.Symbol = "c"
	D       JanOS.Symbol = "d"
	E       JanOS.Symbol = "e"
	F       JanOS.Symbol = "f"
	G       JanOS.Symbol = "g"
	H       JanOS.Symbol = "h"
	I       JanOS.Symbol = "i"
	J       JanOS.Symbol = "j"
	K       JanOS.Symbol = "k"
	L       JanOS.Symbol = "l"
	M       JanOS.Symbol = "m"
	N       JanOS.Symbol = "n"
	O       JanOS.Symbol = "o"
	P       JanOS.Symbol = "p"
	Q       JanOS.Symbol = "q"
	R       JanOS.Symbol = "r"
	S       JanOS.Symbol = "s"
	T       JanOS.Symbol = "t"
	U       JanOS.Symbol = "u"
	V       JanOS.Symbol = "v"
	W       JanOS.Symbol = "w"
	X       JanOS.Symbol = "x"
	Y       JanOS.Symbol = "y"
	Z       JanOS.Symbol = "z"
	Prime   JanOS.Symbol = "`"
	Alpha   JanOS.Symbol = "α"
	Beta    JanOS.Symbol = "β"
	Gamma   JanOS.Symbol = "γ"
	Delta   JanOS.Symbol = "δ"
	Epsilon JanOS.Symbol = "ε"
	Zeta    JanOS.Symbol = "ζ"
	Eta     JanOS.Symbol = "η"
	Theta   JanOS.Symbol = "θ"
	Iota    JanOS.Symbol = "ι"
	Kappa   JanOS.Symbol = "κ"
	Lambda  JanOS.Symbol = "λ"
	Mu      JanOS.Symbol = "μ"
	Nu      JanOS.Symbol = "ν"
	Xi      JanOS.Symbol = "ξ"
	Omicron JanOS.Symbol = "ο"
	Pi      JanOS.Symbol = "π"
	Rho     JanOS.Symbol = "ρ"
	Sigma   JanOS.Symbol = "σ"
	Tau     JanOS.Symbol = "τ"
	Upsilon JanOS.Symbol = "υ"
	Phi     JanOS.Symbol = "φ"
	Chi     JanOS.Symbol = "χ"
	Psi     JanOS.Symbol = "ψ"
	Omega   JanOS.Symbol = "ω"
)
