// Code generated by gen; DO NOT EDIT.

//go:generate go run ./generator -type=Widget -pkg=movement -out=tester.go
package movement

import "fmt"

type WidgetWrapper struct {
	V Widget
}

func (w WidgetWrapper) String() string {
	return fmt.Sprintf("%v", w.V)
}
