// Code generated by 'gen/lexemes/main'; DO NOT EDIT.
package tiny

// Digits are a single placeholder - if you wish to describe any abstract digit, use this interface.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Digit Lexeme

