// Code generated by 'gen/lexemes/main'; DO NOT EDIT.
package tiny

// Lexeme is the most basic unit of the 𝑡𝑖𝑛𝑦 lexicon and represents a single placeholder value in an arithmetic matrix.
// 
// NOTE: All bases from Base2 to Base256 are well-defined in the lexicon, but the most common are aliased for convenience.
//
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Lexeme struct {
	Placeholder uint8
}

// Digits are a single placeholder - if you wish to describe any abstract digit, use this interface.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Digit Lexeme

func (t Digit) String() string { return Lexeme(t).String() } 

// Base2 represents a single binary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base2Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base2 Digit

func (t Base2) String() string { return Digit(t).String() } 

// Base3 represents a single ternary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base3Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base3 Digit

func (t Base3) String() string { return Digit(t).String() } 

// Base4 represents a single quarternary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base4Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base4 Digit

func (t Base4) String() string { return Digit(t).String() } 

// Base5 represents a single quinary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base5Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base5 Digit

func (t Base5) String() string { return Digit(t).String() } 

// Base6 represents a single senary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base6Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base6 Digit

func (t Base6) String() string { return Digit(t).String() } 

// Base7 represents a single septenary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base7Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base7 Digit

func (t Base7) String() string { return Digit(t).String() } 

// Base8 represents a single octal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base8Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base8 Digit

func (t Base8) String() string { return Digit(t).String() } 

// Base9 represents a single nonary placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base9Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base9 Digit

func (t Base9) String() string { return Digit(t).String() } 

// Base10 represents a single decimal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base10Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base10 Digit

func (t Base10) String() string { return Digit(t).String() } 

// Base11 represents a single undecimal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base11Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base11 Digit

func (t Base11) String() string { return Digit(t).String() } 

// Base12 represents a single duodecimal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base12Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base12 Digit

func (t Base12) String() string { return Digit(t).String() } 

// Base13 represents a single tridecimal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base13Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base13 Digit

func (t Base13) String() string { return Digit(t).String() } 

// Base14 represents a single tetradecimal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base14Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base14 Digit

func (t Base14) String() string { return Digit(t).String() } 

// Base15 represents a single pentadecimal placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base15Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base15 Digit

func (t Base15) String() string { return Digit(t).String() } 

// Base16 represents a single base-16 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base16Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base16 Digit

func (t Base16) String() string { return Digit(t).String() } 

// Base17 represents a single base-17 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base17Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base17 Digit

func (t Base17) String() string { return Digit(t).String() } 

// Base18 represents a single base-18 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base18Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base18 Digit

func (t Base18) String() string { return Digit(t).String() } 

// Base19 represents a single base-19 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base19Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base19 Digit

func (t Base19) String() string { return Digit(t).String() } 

// Base20 represents a single base-20 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base20Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base20 Digit

func (t Base20) String() string { return Digit(t).String() } 

// Base21 represents a single base-21 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base21Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base21 Digit

func (t Base21) String() string { return Digit(t).String() } 

// Base22 represents a single base-22 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base22Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base22 Digit

func (t Base22) String() string { return Digit(t).String() } 

// Base23 represents a single base-23 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base23Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base23 Digit

func (t Base23) String() string { return Digit(t).String() } 

// Base24 represents a single base-24 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base24Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base24 Digit

func (t Base24) String() string { return Digit(t).String() } 

// Base25 represents a single base-25 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base25Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base25 Digit

func (t Base25) String() string { return Digit(t).String() } 

// Base26 represents a single base-26 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base26Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base26 Digit

func (t Base26) String() string { return Digit(t).String() } 

// Base27 represents a single base-27 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base27Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base27 Digit

func (t Base27) String() string { return Digit(t).String() } 

// Base28 represents a single base-28 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base28Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base28 Digit

func (t Base28) String() string { return Digit(t).String() } 

// Base29 represents a single base-29 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base29Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base29 Digit

func (t Base29) String() string { return Digit(t).String() } 

// Base30 represents a single base-30 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base30Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base30 Digit

func (t Base30) String() string { return Digit(t).String() } 

// Base31 represents a single base-31 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base31Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base31 Digit

func (t Base31) String() string { return Digit(t).String() } 

// Base32 represents a single base-32 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base32Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base32 Digit

func (t Base32) String() string { return Digit(t).String() } 

// Base33 represents a single base-33 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base33Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base33 Digit

func (t Base33) String() string { return Digit(t).String() } 

// Base34 represents a single base-34 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base34Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base34 Digit

func (t Base34) String() string { return Digit(t).String() } 

// Base35 represents a single base-35 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base35Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base35 Digit

func (t Base35) String() string { return Digit(t).String() } 

// Base36 represents a single base-36 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base36Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base36 Digit

func (t Base36) String() string { return Digit(t).String() } 

// Base37 represents a single base-37 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base37Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base37 Digit

func (t Base37) String() string { return Digit(t).String() } 

// Base38 represents a single base-38 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base38Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base38 Digit

func (t Base38) String() string { return Digit(t).String() } 

// Base39 represents a single base-39 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base39Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base39 Digit

func (t Base39) String() string { return Digit(t).String() } 

// Base40 represents a single base-40 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base40Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base40 Digit

func (t Base40) String() string { return Digit(t).String() } 

// Base41 represents a single base-41 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base41Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base41 Digit

func (t Base41) String() string { return Digit(t).String() } 

// Base42 represents a single base-42 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base42Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base42 Digit

func (t Base42) String() string { return Digit(t).String() } 

// Base43 represents a single base-43 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base43Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base43 Digit

func (t Base43) String() string { return Digit(t).String() } 

// Base44 represents a single base-44 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base44Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base44 Digit

func (t Base44) String() string { return Digit(t).String() } 

// Base45 represents a single base-45 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base45Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base45 Digit

func (t Base45) String() string { return Digit(t).String() } 

// Base46 represents a single base-46 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base46Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base46 Digit

func (t Base46) String() string { return Digit(t).String() } 

// Base47 represents a single base-47 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base47Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base47 Digit

func (t Base47) String() string { return Digit(t).String() } 

// Base48 represents a single base-48 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base48Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base48 Digit

func (t Base48) String() string { return Digit(t).String() } 

// Base49 represents a single base-49 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base49Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base49 Digit

func (t Base49) String() string { return Digit(t).String() } 

// Base50 represents a single base-50 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base50Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base50 Digit

func (t Base50) String() string { return Digit(t).String() } 

// Base51 represents a single base-51 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base51Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base51 Digit

func (t Base51) String() string { return Digit(t).String() } 

// Base52 represents a single base-52 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base52Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base52 Digit

func (t Base52) String() string { return Digit(t).String() } 

// Base53 represents a single base-53 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base53Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base53 Digit

func (t Base53) String() string { return Digit(t).String() } 

// Base54 represents a single base-54 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base54Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base54 Digit

func (t Base54) String() string { return Digit(t).String() } 

// Base55 represents a single base-55 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base55Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base55 Digit

func (t Base55) String() string { return Digit(t).String() } 

// Base56 represents a single base-56 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base56Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base56 Digit

func (t Base56) String() string { return Digit(t).String() } 

// Base57 represents a single base-57 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base57Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base57 Digit

func (t Base57) String() string { return Digit(t).String() } 

// Base58 represents a single base-58 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base58Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base58 Digit

func (t Base58) String() string { return Digit(t).String() } 

// Base59 represents a single base-59 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base59Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base59 Digit

func (t Base59) String() string { return Digit(t).String() } 

// Base60 represents a single base-60 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// 
// - See Base60Digits
// 
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base60 Digit

func (t Base60) String() string { return Digit(t).String() } 

// Base61 represents a single base-61 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base61 Digit

func (t Base61) String() string { return Digit(t).String() } 

// Base62 represents a single base-62 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base62 Digit

func (t Base62) String() string { return Digit(t).String() } 

// Base63 represents a single base-63 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base63 Digit

func (t Base63) String() string { return Digit(t).String() } 

// Base64 represents a single base-64 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base64 Digit

func (t Base64) String() string { return Digit(t).String() } 

// Base65 represents a single base-65 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base65 Digit

func (t Base65) String() string { return Digit(t).String() } 

// Base66 represents a single base-66 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base66 Digit

func (t Base66) String() string { return Digit(t).String() } 

// Base67 represents a single base-67 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base67 Digit

func (t Base67) String() string { return Digit(t).String() } 

// Base68 represents a single base-68 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base68 Digit

func (t Base68) String() string { return Digit(t).String() } 

// Base69 represents a single base-69 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base69 Digit

func (t Base69) String() string { return Digit(t).String() } 

// Base70 represents a single base-70 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base70 Digit

func (t Base70) String() string { return Digit(t).String() } 

// Base71 represents a single base-71 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base71 Digit

func (t Base71) String() string { return Digit(t).String() } 

// Base72 represents a single base-72 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base72 Digit

func (t Base72) String() string { return Digit(t).String() } 

// Base73 represents a single base-73 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base73 Digit

func (t Base73) String() string { return Digit(t).String() } 

// Base74 represents a single base-74 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base74 Digit

func (t Base74) String() string { return Digit(t).String() } 

// Base75 represents a single base-75 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base75 Digit

func (t Base75) String() string { return Digit(t).String() } 

// Base76 represents a single base-76 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base76 Digit

func (t Base76) String() string { return Digit(t).String() } 

// Base77 represents a single base-77 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base77 Digit

func (t Base77) String() string { return Digit(t).String() } 

// Base78 represents a single base-78 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base78 Digit

func (t Base78) String() string { return Digit(t).String() } 

// Base79 represents a single base-79 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base79 Digit

func (t Base79) String() string { return Digit(t).String() } 

// Base80 represents a single base-80 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base80 Digit

func (t Base80) String() string { return Digit(t).String() } 

// Base81 represents a single base-81 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base81 Digit

func (t Base81) String() string { return Digit(t).String() } 

// Base82 represents a single base-82 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base82 Digit

func (t Base82) String() string { return Digit(t).String() } 

// Base83 represents a single base-83 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base83 Digit

func (t Base83) String() string { return Digit(t).String() } 

// Base84 represents a single base-84 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base84 Digit

func (t Base84) String() string { return Digit(t).String() } 

// Base85 represents a single base-85 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base85 Digit

func (t Base85) String() string { return Digit(t).String() } 

// Base86 represents a single base-86 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base86 Digit

func (t Base86) String() string { return Digit(t).String() } 

// Base87 represents a single base-87 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base87 Digit

func (t Base87) String() string { return Digit(t).String() } 

// Base88 represents a single base-88 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base88 Digit

func (t Base88) String() string { return Digit(t).String() } 

// Base89 represents a single base-89 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base89 Digit

func (t Base89) String() string { return Digit(t).String() } 

// Base90 represents a single base-90 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base90 Digit

func (t Base90) String() string { return Digit(t).String() } 

// Base91 represents a single base-91 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base91 Digit

func (t Base91) String() string { return Digit(t).String() } 

// Base92 represents a single base-92 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base92 Digit

func (t Base92) String() string { return Digit(t).String() } 

// Base93 represents a single base-93 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base93 Digit

func (t Base93) String() string { return Digit(t).String() } 

// Base94 represents a single base-94 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base94 Digit

func (t Base94) String() string { return Digit(t).String() } 

// Base95 represents a single base-95 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base95 Digit

func (t Base95) String() string { return Digit(t).String() } 

// Base96 represents a single base-96 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base96 Digit

func (t Base96) String() string { return Digit(t).String() } 

// Base97 represents a single base-97 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base97 Digit

func (t Base97) String() string { return Digit(t).String() } 

// Base98 represents a single base-98 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base98 Digit

func (t Base98) String() string { return Digit(t).String() } 

// Base99 represents a single base-99 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base99 Digit

func (t Base99) String() string { return Digit(t).String() } 

// Base100 represents a single base-100 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base100 Digit

func (t Base100) String() string { return Digit(t).String() } 

// Base101 represents a single base-101 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base101 Digit

func (t Base101) String() string { return Digit(t).String() } 

// Base102 represents a single base-102 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base102 Digit

func (t Base102) String() string { return Digit(t).String() } 

// Base103 represents a single base-103 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base103 Digit

func (t Base103) String() string { return Digit(t).String() } 

// Base104 represents a single base-104 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base104 Digit

func (t Base104) String() string { return Digit(t).String() } 

// Base105 represents a single base-105 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base105 Digit

func (t Base105) String() string { return Digit(t).String() } 

// Base106 represents a single base-106 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base106 Digit

func (t Base106) String() string { return Digit(t).String() } 

// Base107 represents a single base-107 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base107 Digit

func (t Base107) String() string { return Digit(t).String() } 

// Base108 represents a single base-108 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base108 Digit

func (t Base108) String() string { return Digit(t).String() } 

// Base109 represents a single base-109 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base109 Digit

func (t Base109) String() string { return Digit(t).String() } 

// Base110 represents a single base-110 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base110 Digit

func (t Base110) String() string { return Digit(t).String() } 

// Base111 represents a single base-111 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base111 Digit

func (t Base111) String() string { return Digit(t).String() } 

// Base112 represents a single base-112 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base112 Digit

func (t Base112) String() string { return Digit(t).String() } 

// Base113 represents a single base-113 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base113 Digit

func (t Base113) String() string { return Digit(t).String() } 

// Base114 represents a single base-114 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base114 Digit

func (t Base114) String() string { return Digit(t).String() } 

// Base115 represents a single base-115 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base115 Digit

func (t Base115) String() string { return Digit(t).String() } 

// Base116 represents a single base-116 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base116 Digit

func (t Base116) String() string { return Digit(t).String() } 

// Base117 represents a single base-117 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base117 Digit

func (t Base117) String() string { return Digit(t).String() } 

// Base118 represents a single base-118 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base118 Digit

func (t Base118) String() string { return Digit(t).String() } 

// Base119 represents a single base-119 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base119 Digit

func (t Base119) String() string { return Digit(t).String() } 

// Base120 represents a single base-120 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base120 Digit

func (t Base120) String() string { return Digit(t).String() } 

// Base121 represents a single base-121 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base121 Digit

func (t Base121) String() string { return Digit(t).String() } 

// Base122 represents a single base-122 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base122 Digit

func (t Base122) String() string { return Digit(t).String() } 

// Base123 represents a single base-123 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base123 Digit

func (t Base123) String() string { return Digit(t).String() } 

// Base124 represents a single base-124 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base124 Digit

func (t Base124) String() string { return Digit(t).String() } 

// Base125 represents a single base-125 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base125 Digit

func (t Base125) String() string { return Digit(t).String() } 

// Base126 represents a single base-126 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base126 Digit

func (t Base126) String() string { return Digit(t).String() } 

// Base127 represents a single base-127 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base127 Digit

func (t Base127) String() string { return Digit(t).String() } 

// Base128 represents a single base-128 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base128 Digit

func (t Base128) String() string { return Digit(t).String() } 

// Base129 represents a single base-129 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base129 Digit

func (t Base129) String() string { return Digit(t).String() } 

// Base130 represents a single base-130 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base130 Digit

func (t Base130) String() string { return Digit(t).String() } 

// Base131 represents a single base-131 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base131 Digit

func (t Base131) String() string { return Digit(t).String() } 

// Base132 represents a single base-132 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base132 Digit

func (t Base132) String() string { return Digit(t).String() } 

// Base133 represents a single base-133 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base133 Digit

func (t Base133) String() string { return Digit(t).String() } 

// Base134 represents a single base-134 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base134 Digit

func (t Base134) String() string { return Digit(t).String() } 

// Base135 represents a single base-135 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base135 Digit

func (t Base135) String() string { return Digit(t).String() } 

// Base136 represents a single base-136 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base136 Digit

func (t Base136) String() string { return Digit(t).String() } 

// Base137 represents a single base-137 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base137 Digit

func (t Base137) String() string { return Digit(t).String() } 

// Base138 represents a single base-138 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base138 Digit

func (t Base138) String() string { return Digit(t).String() } 

// Base139 represents a single base-139 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base139 Digit

func (t Base139) String() string { return Digit(t).String() } 

// Base140 represents a single base-140 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base140 Digit

func (t Base140) String() string { return Digit(t).String() } 

// Base141 represents a single base-141 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base141 Digit

func (t Base141) String() string { return Digit(t).String() } 

// Base142 represents a single base-142 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base142 Digit

func (t Base142) String() string { return Digit(t).String() } 

// Base143 represents a single base-143 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base143 Digit

func (t Base143) String() string { return Digit(t).String() } 

// Base144 represents a single base-144 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base144 Digit

func (t Base144) String() string { return Digit(t).String() } 

// Base145 represents a single base-145 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base145 Digit

func (t Base145) String() string { return Digit(t).String() } 

// Base146 represents a single base-146 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base146 Digit

func (t Base146) String() string { return Digit(t).String() } 

// Base147 represents a single base-147 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base147 Digit

func (t Base147) String() string { return Digit(t).String() } 

// Base148 represents a single base-148 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base148 Digit

func (t Base148) String() string { return Digit(t).String() } 

// Base149 represents a single base-149 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base149 Digit

func (t Base149) String() string { return Digit(t).String() } 

// Base150 represents a single base-150 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base150 Digit

func (t Base150) String() string { return Digit(t).String() } 

// Base151 represents a single base-151 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base151 Digit

func (t Base151) String() string { return Digit(t).String() } 

// Base152 represents a single base-152 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base152 Digit

func (t Base152) String() string { return Digit(t).String() } 

// Base153 represents a single base-153 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base153 Digit

func (t Base153) String() string { return Digit(t).String() } 

// Base154 represents a single base-154 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base154 Digit

func (t Base154) String() string { return Digit(t).String() } 

// Base155 represents a single base-155 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base155 Digit

func (t Base155) String() string { return Digit(t).String() } 

// Base156 represents a single base-156 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base156 Digit

func (t Base156) String() string { return Digit(t).String() } 

// Base157 represents a single base-157 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base157 Digit

func (t Base157) String() string { return Digit(t).String() } 

// Base158 represents a single base-158 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base158 Digit

func (t Base158) String() string { return Digit(t).String() } 

// Base159 represents a single base-159 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base159 Digit

func (t Base159) String() string { return Digit(t).String() } 

// Base160 represents a single base-160 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base160 Digit

func (t Base160) String() string { return Digit(t).String() } 

// Base161 represents a single base-161 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base161 Digit

func (t Base161) String() string { return Digit(t).String() } 

// Base162 represents a single base-162 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base162 Digit

func (t Base162) String() string { return Digit(t).String() } 

// Base163 represents a single base-163 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base163 Digit

func (t Base163) String() string { return Digit(t).String() } 

// Base164 represents a single base-164 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base164 Digit

func (t Base164) String() string { return Digit(t).String() } 

// Base165 represents a single base-165 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base165 Digit

func (t Base165) String() string { return Digit(t).String() } 

// Base166 represents a single base-166 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base166 Digit

func (t Base166) String() string { return Digit(t).String() } 

// Base167 represents a single base-167 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base167 Digit

func (t Base167) String() string { return Digit(t).String() } 

// Base168 represents a single base-168 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base168 Digit

func (t Base168) String() string { return Digit(t).String() } 

// Base169 represents a single base-169 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base169 Digit

func (t Base169) String() string { return Digit(t).String() } 

// Base170 represents a single base-170 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base170 Digit

func (t Base170) String() string { return Digit(t).String() } 

// Base171 represents a single base-171 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base171 Digit

func (t Base171) String() string { return Digit(t).String() } 

// Base172 represents a single base-172 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base172 Digit

func (t Base172) String() string { return Digit(t).String() } 

// Base173 represents a single base-173 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base173 Digit

func (t Base173) String() string { return Digit(t).String() } 

// Base174 represents a single base-174 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base174 Digit

func (t Base174) String() string { return Digit(t).String() } 

// Base175 represents a single base-175 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base175 Digit

func (t Base175) String() string { return Digit(t).String() } 

// Base176 represents a single base-176 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base176 Digit

func (t Base176) String() string { return Digit(t).String() } 

// Base177 represents a single base-177 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base177 Digit

func (t Base177) String() string { return Digit(t).String() } 

// Base178 represents a single base-178 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base178 Digit

func (t Base178) String() string { return Digit(t).String() } 

// Base179 represents a single base-179 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base179 Digit

func (t Base179) String() string { return Digit(t).String() } 

// Base180 represents a single base-180 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base180 Digit

func (t Base180) String() string { return Digit(t).String() } 

// Base181 represents a single base-181 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base181 Digit

func (t Base181) String() string { return Digit(t).String() } 

// Base182 represents a single base-182 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base182 Digit

func (t Base182) String() string { return Digit(t).String() } 

// Base183 represents a single base-183 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base183 Digit

func (t Base183) String() string { return Digit(t).String() } 

// Base184 represents a single base-184 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base184 Digit

func (t Base184) String() string { return Digit(t).String() } 

// Base185 represents a single base-185 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base185 Digit

func (t Base185) String() string { return Digit(t).String() } 

// Base186 represents a single base-186 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base186 Digit

func (t Base186) String() string { return Digit(t).String() } 

// Base187 represents a single base-187 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base187 Digit

func (t Base187) String() string { return Digit(t).String() } 

// Base188 represents a single base-188 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base188 Digit

func (t Base188) String() string { return Digit(t).String() } 

// Base189 represents a single base-189 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base189 Digit

func (t Base189) String() string { return Digit(t).String() } 

// Base190 represents a single base-190 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base190 Digit

func (t Base190) String() string { return Digit(t).String() } 

// Base191 represents a single base-191 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base191 Digit

func (t Base191) String() string { return Digit(t).String() } 

// Base192 represents a single base-192 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base192 Digit

func (t Base192) String() string { return Digit(t).String() } 

// Base193 represents a single base-193 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base193 Digit

func (t Base193) String() string { return Digit(t).String() } 

// Base194 represents a single base-194 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base194 Digit

func (t Base194) String() string { return Digit(t).String() } 

// Base195 represents a single base-195 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base195 Digit

func (t Base195) String() string { return Digit(t).String() } 

// Base196 represents a single base-196 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base196 Digit

func (t Base196) String() string { return Digit(t).String() } 

// Base197 represents a single base-197 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base197 Digit

func (t Base197) String() string { return Digit(t).String() } 

// Base198 represents a single base-198 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base198 Digit

func (t Base198) String() string { return Digit(t).String() } 

// Base199 represents a single base-199 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base199 Digit

func (t Base199) String() string { return Digit(t).String() } 

// Base200 represents a single base-200 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base200 Digit

func (t Base200) String() string { return Digit(t).String() } 

// Base201 represents a single base-201 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base201 Digit

func (t Base201) String() string { return Digit(t).String() } 

// Base202 represents a single base-202 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base202 Digit

func (t Base202) String() string { return Digit(t).String() } 

// Base203 represents a single base-203 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base203 Digit

func (t Base203) String() string { return Digit(t).String() } 

// Base204 represents a single base-204 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base204 Digit

func (t Base204) String() string { return Digit(t).String() } 

// Base205 represents a single base-205 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base205 Digit

func (t Base205) String() string { return Digit(t).String() } 

// Base206 represents a single base-206 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base206 Digit

func (t Base206) String() string { return Digit(t).String() } 

// Base207 represents a single base-207 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base207 Digit

func (t Base207) String() string { return Digit(t).String() } 

// Base208 represents a single base-208 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base208 Digit

func (t Base208) String() string { return Digit(t).String() } 

// Base209 represents a single base-209 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base209 Digit

func (t Base209) String() string { return Digit(t).String() } 

// Base210 represents a single base-210 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base210 Digit

func (t Base210) String() string { return Digit(t).String() } 

// Base211 represents a single base-211 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base211 Digit

func (t Base211) String() string { return Digit(t).String() } 

// Base212 represents a single base-212 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base212 Digit

func (t Base212) String() string { return Digit(t).String() } 

// Base213 represents a single base-213 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base213 Digit

func (t Base213) String() string { return Digit(t).String() } 

// Base214 represents a single base-214 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base214 Digit

func (t Base214) String() string { return Digit(t).String() } 

// Base215 represents a single base-215 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base215 Digit

func (t Base215) String() string { return Digit(t).String() } 

// Base216 represents a single base-216 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base216 Digit

func (t Base216) String() string { return Digit(t).String() } 

// Base217 represents a single base-217 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base217 Digit

func (t Base217) String() string { return Digit(t).String() } 

// Base218 represents a single base-218 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base218 Digit

func (t Base218) String() string { return Digit(t).String() } 

// Base219 represents a single base-219 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base219 Digit

func (t Base219) String() string { return Digit(t).String() } 

// Base220 represents a single base-220 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base220 Digit

func (t Base220) String() string { return Digit(t).String() } 

// Base221 represents a single base-221 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base221 Digit

func (t Base221) String() string { return Digit(t).String() } 

// Base222 represents a single base-222 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base222 Digit

func (t Base222) String() string { return Digit(t).String() } 

// Base223 represents a single base-223 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base223 Digit

func (t Base223) String() string { return Digit(t).String() } 

// Base224 represents a single base-224 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base224 Digit

func (t Base224) String() string { return Digit(t).String() } 

// Base225 represents a single base-225 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base225 Digit

func (t Base225) String() string { return Digit(t).String() } 

// Base226 represents a single base-226 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base226 Digit

func (t Base226) String() string { return Digit(t).String() } 

// Base227 represents a single base-227 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base227 Digit

func (t Base227) String() string { return Digit(t).String() } 

// Base228 represents a single base-228 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base228 Digit

func (t Base228) String() string { return Digit(t).String() } 

// Base229 represents a single base-229 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base229 Digit

func (t Base229) String() string { return Digit(t).String() } 

// Base230 represents a single base-230 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base230 Digit

func (t Base230) String() string { return Digit(t).String() } 

// Base231 represents a single base-231 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base231 Digit

func (t Base231) String() string { return Digit(t).String() } 

// Base232 represents a single base-232 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base232 Digit

func (t Base232) String() string { return Digit(t).String() } 

// Base233 represents a single base-233 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base233 Digit

func (t Base233) String() string { return Digit(t).String() } 

// Base234 represents a single base-234 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base234 Digit

func (t Base234) String() string { return Digit(t).String() } 

// Base235 represents a single base-235 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base235 Digit

func (t Base235) String() string { return Digit(t).String() } 

// Base236 represents a single base-236 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base236 Digit

func (t Base236) String() string { return Digit(t).String() } 

// Base237 represents a single base-237 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base237 Digit

func (t Base237) String() string { return Digit(t).String() } 

// Base238 represents a single base-238 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base238 Digit

func (t Base238) String() string { return Digit(t).String() } 

// Base239 represents a single base-239 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base239 Digit

func (t Base239) String() string { return Digit(t).String() } 

// Base240 represents a single base-240 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base240 Digit

func (t Base240) String() string { return Digit(t).String() } 

// Base241 represents a single base-241 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base241 Digit

func (t Base241) String() string { return Digit(t).String() } 

// Base242 represents a single base-242 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base242 Digit

func (t Base242) String() string { return Digit(t).String() } 

// Base243 represents a single base-243 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base243 Digit

func (t Base243) String() string { return Digit(t).String() } 

// Base244 represents a single base-244 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base244 Digit

func (t Base244) String() string { return Digit(t).String() } 

// Base245 represents a single base-245 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base245 Digit

func (t Base245) String() string { return Digit(t).String() } 

// Base246 represents a single base-246 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base246 Digit

func (t Base246) String() string { return Digit(t).String() } 

// Base247 represents a single base-247 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base247 Digit

func (t Base247) String() string { return Digit(t).String() } 

// Base248 represents a single base-248 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base248 Digit

func (t Base248) String() string { return Digit(t).String() } 

// Base249 represents a single base-249 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base249 Digit

func (t Base249) String() string { return Digit(t).String() } 

// Base250 represents a single base-250 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base250 Digit

func (t Base250) String() string { return Digit(t).String() } 

// Base251 represents a single base-251 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base251 Digit

func (t Base251) String() string { return Digit(t).String() } 

// Base252 represents a single base-252 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base252 Digit

func (t Base252) String() string { return Digit(t).String() } 

// Base253 represents a single base-253 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base253 Digit

func (t Base253) String() string { return Digit(t).String() } 

// Base254 represents a single base-254 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base254 Digit

func (t Base254) String() string { return Digit(t).String() } 

// Base255 represents a single base-255 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base255 Digit

func (t Base255) String() string { return Digit(t).String() } 

// Base256 represents a single base-256 placeholder Digit.
// 
// NOTE: All 𝑡𝑖𝑛𝑦 placeholder lexeme digits are hexadecimal.
// See Lexeme, Digit, Binary, Ternary, Octal, Decimal, Hexadecimal, and Sexagesimal
type Base256 Digit

func (t Base256) String() string { return Digit(t).String() } 

